### ISSUE TITLE
Support legacy interface for storing files in REST

### ISSUE THREAD

**Issue by glebshalyganov** [Haulmont/jmix-cuba#48]
New implementations of `io.jmix.rest.api.controller.FileDownloadController` and `FileUploadController` work with the new file storage in which files are denoted by `URI` file reference.
Compatibility controllers should work with the `FileDescriptor` ids.

**Comment by artemglinov** [comment]
### NOTE

Legacy CUBA REST API FileUploadController and FileDownloadController are accessed via a URL `/v2/files`. One needs to use

1. POST HTTP-method to upload a file;

2. GET HTTP-method to download a file (it's necessary to append `/{fileDescriptorId}` to `/v2/files` URL in this case).

**Comment by maistrenkoIulia** [comment]
@artemglinov please, provide qa notes

**Comment by artemglinov** [comment]
### **QA Notes**

In order to test files uploading/downloading, one needs to create a role with the following resource policies:

- "create" and "read" permissions applied to `sys$FileDescriptor` entity;
- specific permissions `rest.fileDownload.enabled` and `rest.fileUpload.enabled` (besides of standard `rest.enabled`).

**Uploading files**

Generally, file contents are simply put in the request body. In a special case of `multipart/form-data` Content-Type it is necessary to place it in the "file" part.

After authorization and addition of the file contents, send a POST request (URL ends in `/rest/cuba/files`). The response body will contain a File Descriptor ID required for file downloading.

**Downloading files**

Files downloading is carried out by sending a GET request to the endpoint located at URL for uploading + ID of the File Descriptor appended (like `/rest/cuba/files/{fileDescriptorId}`). File contents must be displayed in the response body.

**Comment by maistrenkoIulia** [comment]
verified
